media: img
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, layout, date, description, categories ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: 'post'
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: categories
        label: Categories
        type: string