# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mateusz-nejman.github.io'
baseurl: ''
title: 'Mateusz Nejman Blog'
description: 'I am Mateusz Nejman and this is my personal place for sharing my ideas and knowledge with you'
permalink: pretty
logo: "/img/icon.png"
fonts:
  preconnect_urls:
  - https://fonts.googleapis.com
  - https://fonts.gstatic.com
styles:
- https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap
- /js/highlightjs/styles/github.css
- /js/highlightjs/styles/ssms.css
scripts:
- /js/highlightjs/highlight.min.js
- /js/highlightjs/languages/cpp.min.js
- /js/highlightjs/languages/csharp.min.js
- /js/highlightjs/languages/json.min.js
- /js/highlightjs/languages/markdown.min.js
- /js/highlightjs/languages/plaintext.min.js
- /js/highlightjs/languages/powershell.min.js
- //unpkg.com/darkreader@4.9.40/darkreader.js
# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "/img/banner.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

kramdown:
  syntax_highlighter_opts:
    disable: true